### ISSUE TITLE
Testing Kyber with KAT could be sped up

### ISSUE THREAD

**Issue by GiacomoPope** [GiacomoPope/kyber-py#23]
At the moment we parse all data and compare everything line by line. It would be better to recreate the KAT file within the test and then compare the hash of all this data with the hash of the precomputed KAT files.

**Comment by GiacomoPope** [comment]
I quickly added a file to do this here: https://github.com/GiacomoPope/kyber-py/commit/e378e175defbffd6eb2333321fc79c8619e58a21

We should decide about pytest versus unittest and integrate it into the CI

**Comment by tomato42** [comment]
In my experience parsing the data from the file isn't slow enough to really impact the testing; the cryptographic operations are much more impactful
