### ISSUE TITLE
Documentation needs love and care

### ISSUE THREAD

**Issue by GiacomoPope** [GiacomoPope/kyber-py#27]
https://kyber-py.readthedocs.io/en/latest/

**Comment by GiacomoPope** [comment]
I added the main modules after linking, but apparently didn't connect it so it could automatically find all the python files for each module, so the docs are particularly broken after the latest refactoring... @tomato42

**Comment by tomato42** [comment]
hmm, if we're moving things around anyway, maybe we could put all the sources into the `src` dir?

you can generate the module API files using
```
cd docs/
sphinx-apidoc -o source/ ../
```

**Comment by GiacomoPope** [comment]
Hmm I tried this and now there docs seem to have some structure but no information. I'm not experienced with Sphinx... I'll be more useful writing the docstrings themselves I think
