### ISSUE TITLE
Swap unittest for pytest and aim for high coverage

### ISSUE THREAD

**Issue by GiacomoPope** [GiacomoPope/kyber-py#29]

**Comment by tomato42** [comment]
there's no need for swapping, you can execute unittest tests with pytest and that's the end of it :)

**Comment by GiacomoPope** [comment]
Would be nice to have consistency with all the tests though :)

**Comment by tomato42** [comment]
I don't know... while I like the parametrisation of tests that pytest allows, I find the setUp() for the unittest test class much cleaner for code reuse

**Comment by jpgoldberg** [comment]
In #35, I have a fix that gets tests to run properly with pytest without changing how they behave with unittest. `test_kat_files` was named in ways that created problems.

**Comment by GiacomoPope** [comment]
We're using pytest in the CLI now, so im going to close this.
