### ISSUE TITLE
Have default values shown at module level

### ISSUE THREAD

**Issue by GiacomoPope** [GiacomoPope/kyber-py#53]
For example we have: https://kyber-py.readthedocs.io/en/latest/kyber_py.ml_kem.html

The header "Module contents" is empty, but it would be nice to show that really we can import `ML_KEM128` etc directly from `kyber_py.ml_kem` - what's the best way to make Sphinx see this?

**Comment by tomato42** [comment]
I think it's by defining `__all__`

But in general just having the module docstrings would help already

**Comment by tomato42** [comment]
The ML-KEM parameters are actually documented in the docs now, so I've added the same for Kyber in https://github.com/GiacomoPope/kyber-py/pull/72
