### ISSUE TITLE
Inconsistent names?

### ISSUE THREAD

**Issue by tomato42** [GiacomoPope/kyber-py#57]
https://github.com/GiacomoPope/kyber-py/blob/6f6e14ec598040e34979c9fbf407af52af3299b1/src/kyber_py/ml_kem/default_parameters.py#L6-L14

The names of the parameter sets in NIST 203-ipd are (lines 619-620):
 * ML-KEM-512
 * ML-KEM-768
 * ML-KEM-1024

Why we're not naming them `ML_KEM_512`, `ML_KEM_768`, and `ML_KEM_1024`?

**Comment by GiacomoPope** [comment]
Ahh this might have just been a silly mistake I agree with the names you suggest here
