### ISSUE TITLE
Common Python formatting

### ISSUE THREAD

**Issue by jpgoldberg** [GiacomoPope/kyber-py#81]
I am finding myself in a sea of merge conflicts even when I think I am making a minor change., I suspect that some of this is due to me (tacitly) using a different fill formatting convention and getting loads of whitespace. That is, I am seeing diffs reported where I do not need a difference.

I would like to recommend that we settle on a common python formatting and linting system. Personally, I would prefer using [ruff](https://docs.astral.sh/ruff/) and we create a `ruff.toml` file for any non-default settings and for settling on a line length. But I will go along with what others prefer, as long as we settle on something.

**Comment by tomato42** [comment]
there's already `black` being used, executed in CI...

also, why you're getting merge conflicts when doing small changes?! are you sure your `main` branch is up to date?

**Comment by GiacomoPope** [comment]
The good news is that I've done most (all?) the things I want so there will be less change

Maybe we should add a black config file as @tomato42 set the line length to 79 which is non-standard

**Comment by GiacomoPope** [comment]
I'm not sure where we are with this, but I think it can be closed unless you have concerns @jpgoldberg

**Comment by tomato42** [comment]
+1 for closing
